[tool.poetry]
name = "streamlit-apps"
version = "0.1.0"
description = ""
authors = ["Pond <chatchai.chailungka@aig.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.49.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
